aliases:
  # Cache Management
  - &restore-yarn-cache
    keys:
      - v1-yarn-cache-{{ arch }}-{{ checksum "package.json" }}
      - v1-yarn-cache-{{ arch }}
  - &save-yarn-cache
    paths:
      - ~/.cache/yarn
    key: v1-yarn-cache-{{ arch }}-{{ checksum "package.json" }}
  - &restore-gradle-cache
    keys:
      - v1-gradle-{{ arch }}-{{ checksum "android/build.gradle" }}-{{ checksum "android/app/build.gradle" }}
      # Fallback in case checksum fails
      - v1-gradle-{{ arch }}-
      # Fallback in case this is a first-time run on a fork
      - v1-gradle-master-
  - &save-gradle-cache
    paths:
      - ~/.gradle
    key: v1-gradle-{{ arch }}-{{ checksum "android/build.gradle" }}-{{ checksum "android/app/build.gradle" }}

version: 2
jobs:
  android:
    working_directory: ~/repo
    docker:
      - image: reactnativecommunity/react-native-android
    steps:
      - checkout
      - run: npm i -g envinfo && envinfo
      - restore-cache: *restore-yarn-cache
      - restore-cache: *restore-gradle-cache
      - run: yarn install
      - run: cd android && chmod +x gradlew && ./gradlew assembleRelease
      - save-cache: *save-yarn-cache
      - save-cache: *save-gradle-cache

workflows:
  version: 2
  build_and_test:
    jobs:
      - android
